language: node_js
node_js:
  - "0.10"
  - "0.11"

before_script:
  - npm install -g istanbul coveralls
  - npm install -g mocha
  - npm install -g codeclimate
  - npm install

after_success:
  - make coveralls
script:
  - npm test
  - make test-cov

addons:
  code_climate:
    repo_token: 5363cf73e30ba0703d003508

after_script:
  - cat coverage/lcov.info | codeclimate