language: node_js
node_js:
  - "0.10"
  - "0.11"

before_script:
  - npm install -g istanbul coveralls
  - npm install -g mocha
  - npm install

after_success:
  - make coveralls
script:
  - npm test
  - make test-cov

addons:
  code_climate:
    repo_token: 0860a573fd01a1fbafc298b7c40cd0c1fd8b25e5f53a5e8346d3b42cb40ab48e

after_script:
  - cat coverage/lcov.info | codeclimate